export const ADD_DELIVERY_FORM_DETAILS = "ADD_DELIVERY_FORM_DETAILS";
export const ADD_SHIPPING_FORM_DETAILS = "ADD_SHIPPING_FORM_DETAILS";
export const DELETE_ORDER_FORM_DETAILS = "DELETE_ORDER_FORM_DETAILS";
